query Companies($id: ID!) {
  company(id: $id) {
    id
    company_name
    location
    company_logo {
      url
    }
		full_description
    content {
      id
      title
      body_paragraph 
      image {
        url
      }
      image_caption
    }
    social {
      id
      icon {
        fab_fas
        fa_name
      }
 
      link
      isHover
    }
    card {
      id
      title
      bullet {
        id
        text
      }
    }
  }
}