query Companies($company_name: String!) {
  companies(where: {company_name_contains: $company_name}){
    id
    publish
    company_name
    location
    short_description
    company_logo {
      url
    }
  }
}